param([ValidateSet('core','full')][string]$Mode='core')

$ErrorActionPreference='Stop'
$root=Split-Path $PSScriptRoot -Parent
$runtime=Join-Path $root '.runtime'; $logs=Join-Path $root 'logs'
New-Item -ItemType Directory -Force $runtime,$logs | Out-Null
function Test-HttpOk($Url) { try { (Invoke-WebRequest $Url -UseBasicParsing -TimeoutSec 3).StatusCode -eq 200 } catch { $false } }
function Get-PortOwner($Port) { (Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue | Select-Object -First 1).OwningProcess }
function Get-State($Name) { $path=Join-Path $runtime "$Name.json"; if(-not(Test-Path $path)){return $null}; try { Get-Content -Raw $path|ConvertFrom-Json } catch { Write-Warning "Ignoring unreadable state: $path"; $null } }
function Test-StateIdentity($State) {
    if($null -eq $State -or -not $State.pid -or -not $State.processStartTimeUtc -or -not $State.port){return $false}
    try {$p=Get-Process -Id ([int]$State.pid) -EA Stop;$recorded=if($State.processStartTimeUtcTicks){[DateTime]::new([int64]$State.processStartTimeUtcTicks,[DateTimeKind]::Utc)}else{[DateTime]::SpecifyKind(([DateTime]$State.processStartTimeUtc),[DateTimeKind]::Utc)};if([Math]::Abs(($p.StartTime.ToUniversalTime()-$recorded).TotalSeconds)-gt 2){return $false};if((Get-PortOwner ([int]$State.port)) -ne $p.Id){return $false};$cim=Get-CimInstance Win32_Process -Filter "ProcessId=$($p.Id)" -EA Stop;if($State.executablePath -and $cim.ExecutablePath -and $cim.ExecutablePath -ne $State.executablePath){return $false};foreach($marker in @($State.expectedCommandMarkers)){if($marker -like '--port *'){continue};if(-not $cim.CommandLine -or $cim.CommandLine -notlike "*$marker*"){return $false}};return $true}catch{return $false}
}
function Save-State($Name,$Process,$Directory,$Port,$Markers) {$started=$Process.StartTime.ToUniversalTime();$state=@{schemaVersion=1;pid=$Process.Id;service=$Name;processStartTimeUtc=$started.ToString('o');processStartTimeUtcTicks=$started.Ticks;executablePath=$Process.Path;workingDirectory=$Directory;expectedCommandMarkers=@($Markers);port=$Port;createdBy='scripts/start-dev.ps1';stateFileCreatedAtUtc=[DateTime]::UtcNow.ToString('o')};$tmp=Join-Path $runtime "$Name.tmp";$final=Join-Path $runtime "$Name.json";$state|ConvertTo-Json|Set-Content $tmp -Encoding UTF8;Move-Item $tmp $final -Force}
function Test-Adoptable($Name,$Port) {try{$listenerPid=Get-PortOwner $Port;if(-not $listenerPid){return $null};$p=Get-Process -Id $listenerPid -EA Stop;$cim=Get-CimInstance Win32_Process -Filter "ProcessId=$listenerPid" -EA Stop;if($Name -eq 'api'){if($cim.ExecutablePath -eq 'D:\Anaconda3\envs\kghub\python.exe' -and $cim.CommandLine -like '*uvicorn*' -and $cim.CommandLine -like '*api.main:app*'){return $p}}elseif($Name -eq 'frontend'){if($cim.ExecutablePath -like '*node.exe' -and $cim.CommandLine -like "*$root\fontend\vue-aapp\node_modules*vue-cli-service.js*" -and $cim.CommandLine -like '* serve*'){return $p}}}catch{};return $null}
function Confirm-Existing($Name,$Port,$Url,$Directory,$Markers) { $state=Get-State $Name;if(Test-HttpOk $Url){if(Test-StateIdentity $state){Write-Host "$Name already running (managed PID $($state.pid)).";return $true};$candidate=Test-Adoptable $Name $Port;if($candidate){Save-State $Name $candidate $Directory $Port $Markers;Write-Host "$Name adopted after exact command and listener verification (PID $($candidate.Id)).";return $true};throw "$Name is healthy on port $Port but is not verified by its PID state. It will not be adopted or replaced."};if(Get-PortOwner $Port){if(Test-StateIdentity $state){throw "$Name PID $($state.pid) owns port $Port but is unhealthy. Run stop-dev.ps1 and inspect logs before retrying."};throw "Port $Port is occupied by an unmanaged or unverifiable process."};return $false}
function Wait-ForService($Name,$Port,$Url,$Process) {for($i=0;$i -lt 30;$i++){$listenerPid=Get-PortOwner $Port;if($listenerPid -and(Test-HttpOk $Url)){return (Get-Process -Id $listenerPid -EA Stop)};Start-Sleep 1};Stop-Process -Id $Process.Id -EA SilentlyContinue;throw "$Name did not become healthy; see $logs."}
function Wait-ForUrl($Name,$Url) {for($i=0;$i -lt 60;$i++){if(Test-HttpOk $Url){return};Start-Sleep 1};throw "$Name did not become ready at $Url."}
foreach($c in 'docker','conda','node','npm'){if(-not(Get-Command $c -EA SilentlyContinue)){throw "Missing $c"}};if(-not(Test-Path "$root/python/.env")){throw 'Missing python/.env'}
$services=if($Mode -eq 'full'){'mongodb','neo4j','chromadb','zookeeper','kafka'}else{'mongodb','neo4j','chromadb'};Push-Location $root;try{docker compose up -d $services}finally{Pop-Location}
Wait-ForUrl 'Chroma' 'http://127.0.0.1:8000/api/v2/auth/identity'
Write-Host 'Chroma is ready.'
$noProxy=(@($env:NO_PROXY -split ',';'localhost';'127.0.0.1';'::1')|Where-Object {$_}|Select-Object -Unique)-join ','
$env:NO_PROXY=$noProxy; $env:no_proxy=$noProxy
if(-not(Confirm-Existing 'api' 8080 'http://127.0.0.1:8080/api/health' "$root/python" @('uvicorn','api.main:app'))){Write-Host 'Starting API process.';$python='D:\Anaconda3\envs\kghub\python.exe';if(-not(Test-Path $python)){throw "Missing kghub Python: $python"};$p=Start-Process $python -ArgumentList '-m','uvicorn','api.main:app','--host','127.0.0.1','--port','8080' -WorkingDirectory "$root/python" -RedirectStandardOutput "$logs/api.log" -RedirectStandardError "$logs/api.err.log" -WindowStyle Hidden -PassThru;$listener=Wait-ForService 'API' 8080 'http://127.0.0.1:8080/api/health' $p;Save-State 'api' $listener "$root/python" 8080 @('uvicorn','api.main:app','--port 8080')}
Write-Host 'API is healthy.'
if(-not(Confirm-Existing 'frontend' 8081 'http://127.0.0.1:8081/' "$root/fontend/vue-aapp" @('vue-cli-service.js','serve'))){Write-Host 'Starting frontend process.';$entry="$root/fontend/vue-aapp/node_modules/@vue/cli-service/bin/vue-cli-service.js";if(-not(Test-Path $entry)){throw "Missing frontend dependency: $entry. Run npm install in fontend/vue-aapp."};$node=(Get-Command node -EA Stop).Source;$p=Start-Process $node -ArgumentList $entry,'serve','--host','127.0.0.1','--port','8081' -WorkingDirectory "$root/fontend/vue-aapp" -RedirectStandardOutput "$logs/frontend.log" -RedirectStandardError "$logs/frontend.err.log" -WindowStyle Hidden -PassThru;$listener=Wait-ForService 'Frontend' 8081 'http://127.0.0.1:8081/' $p;Save-State 'frontend' $listener "$root/fontend/vue-aapp" 8081 @('vue-cli-service.js','serve','--port 8081')}
Write-Host 'Frontend is healthy.'
for($i=0;$i -lt 60 -and -not(Test-HttpOk 'http://127.0.0.1:8080/api/health/ready');$i++){Start-Sleep 2};if(-not(Test-HttpOk 'http://127.0.0.1:8080/api/health/ready')){throw "API is not ready; see $logs/api.log"};if(-not(Test-HttpOk 'http://127.0.0.1:8081/api/health')){throw 'Frontend is running but its API proxy is not healthy.'};if($Mode -eq 'full'){Write-Warning 'Kafka infrastructure is running; CDC worker is NOT IMPLEMENTED and is not reported healthy.'}
